source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# AWS SDK
gem 'aws-sdk', '~> 2'

# ORM for DynamoDB
gem 'dynamoid', '~> 2'

gem 'rails-api'

# Easier API calling
gem 'http'

# Pusher API
gem 'pusher'

gem 'rufus-scheduler'

# Production/Development server that supports concurrency
gem 'puma'

# Easier API calling
gem 'unirest'

# Async Jobs
gem 'sucker_punch', '~> 2.0'

# Memcache
gem 'dalli'

# Puma with memcache
gem 'connection_pool'

gem 'rubocop', require: false
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails'w, group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
